### ISSUE TITLE
td, th, tr - These tags' .example-output and .example-code is empty

### ISSUE THREAD

**Issue by tarequemdhanif** [jgthms/html-reference#15]
I see that `.example-output` and `.example-code` is empty in **td**, **th**, **tr** tags.

**Links**
1. [td](http://htmlreference.io/tables/#td)
2. [th](http://htmlreference.io/tables/#th)
3. [tr](http://htmlreference.io/tables/#tr)

**Comment by udus97** [comment]
The missing .example-output and .example-code are intentionally left blank/missing because examples of how td,th and tr should work have been presented in the preceding examples.

**Comment by tarequemdhanif** [comment]
Got it.
